# Generated by Django 5.1.3 on 2024-12-06 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apartamentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('longtitle', models.CharField(blank=True, max_length=255, verbose_name='Расширенный')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('introtext', models.CharField(blank=True, max_length=255, verbose_name='Аннотация')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('img', models.ImageField(upload_to='apartaments/%Y/%m/%d', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Апартамент',
                'verbose_name_plural': 'Апартаменты',
                'ordering': ['time_created', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Резерв')),
                ('ships_crew', models.CharField(max_length=200, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, upload_to='img_doctors/%Y/%m/%d', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Статус лечения')),
            ],
            options={
                'verbose_name': 'Статус лечения',
                'verbose_name_plural': 'Статусы лечения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Вид лечения')),
            ],
            options={
                'verbose_name': 'Вид лечения',
                'verbose_name_plural': 'Виды лечения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('video_link', models.CharField(max_length=255, verbose_name='You-tube')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-time_created', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ImgPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('image', models.ImageField(upload_to='post_photos/%Y/%m', verbose_name='Фото')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.pageitem', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Фото постов',
                'verbose_name_plural': 'Фото постов',
                'ordering': ['-date_modified', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('image', models.ImageField(upload_to='gall_photos/%Y/%m', verbose_name='Фото')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.apartamentitem', verbose_name='Апартаменты')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии апартаментов',
                'ordering': ['-date_modified', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=15, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('birth_day', models.DateField(blank=True, verbose_name='ДР')),
                ('emails', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.IntegerField(help_text='Введите номер телефона', verbose_name='Телефон')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('photo', models.ImageField(blank=True, upload_to='patients_img/%Y/%m/%d/', verbose_name='Фото')),
                ('reminder_days', models.DateTimeField(blank=True, verbose_name='Напоминание')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.country', verbose_name='Страна')),
                ('treatment_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.treatmentstatus', verbose_name='Статус лечения')),
                ('treatment_types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.treatmenttype', verbose_name='Вид лечения')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
