# Generated by Django 5.1.3 on 2024-12-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('name', models.CharField(max_length=200)),
                ('ships_crew', models.CharField(max_length=200, verbose_name='Должность')),
                ('img_name', models.ImageField(blank=True, upload_to='img_doctors/%Y/%m/%d', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
